version: '3.8'

services:
  frontend:
    build:
      context: ./israel-hayom-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./israel-hayom-be
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
